stages:
  - DeployDevelop

DeployDevelop:
  stage: DeployDevelop
  image: 0868124511/amela-node:18.16-buster-slim
  only: ['develop']
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$HOST_DEV" >> ~/.ssh/known_hosts
    - echo "$PRIVATE_DEPLOY_KEY_DEV" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - echo "$DEV_ENV" > .env
    - yarn install
    - CI= && yarn build
    - rsync --progress -avzh -e "ssh -i ~/.ssh/id_rsa" --rsync-path="sudo rsync" --exclude={.git,node_modules} . ubuntu@"$HOST_DEV":/var/www/html/task-manager-frontend